[package]
name = "em"
version = "0.1.0"
authors = ["Aleksander Fular <ntszar@gmail.com>", "Piotr Mis <piotrekmis@gmail.com>"]

[dependencies]
itertools = "0.7"
serde = "1"
serde_derive = "1"

smart_enum_derive = {path = "smart_enum_derive"}
